//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImdbParser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImdbParser.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visos parinktys turi būti unikalios ir negali kartotis..
        /// </summary>
        internal static string All_options_must_be_unique {
            get {
                return ResourceManager.GetString("All_options_must_be_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komanda &apos;{0}&apos; turi turėti parinktį (-is) &apos;{1}&apos;..
        /// </summary>
        internal static string Command_must_have_option {
            get {
                return ResourceManager.GetString("Command_must_have_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepavyko gauti filme vaidinusių aktorių..
        /// </summary>
        internal static string Failed_to_get_cast {
            get {
                return ResourceManager.GetString("Failed_to_get_cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepavyko gauti filmo režisierių..
        /// </summary>
        internal static string Failed_to_get_directors {
            get {
                return ResourceManager.GetString("Failed_to_get_directors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepavyko gauti filmo žanrų..
        /// </summary>
        internal static string Failed_to_get_genres {
            get {
                return ResourceManager.GetString("Failed_to_get_genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepavyko gauti filmo pavadinimo..
        /// </summary>
        internal static string Failed_to_get_title {
            get {
                return ResourceManager.GetString("Failed_to_get_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepavyko gauti filmo išleidimo metų..
        /// </summary>
        internal static string Failed_to_get_years {
            get {
                return ResourceManager.GetString("Failed_to_get_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurodytas failas neegzistuoja..
        /// </summary>
        internal static string File_does_not_exist {
            get {
                return ResourceManager.GetString("File_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komanda &apos;{0}&apos; turi turėti {1} parametrą (-us)..
        /// </summary>
        internal static string Invalid_command_parameters_count {
            get {
                return ResourceManager.GetString("Invalid_command_parameters_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visos kalbos turi būti unikalios ir negali kartotis..
        /// </summary>
        internal static string Language_not_unique {
            get {
                return ResourceManager.GetString("Language_not_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuoroda turi turėti failo kelią..
        /// </summary>
        internal static string Link_has_no_path {
            get {
                return ResourceManager.GetString("Link_has_no_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MKV Tool Nix įdiegta, tačiau nepavyko rasti failo &apos;{0}&apos;..
        /// </summary>
        internal static string MKV_Tool_Nix_executable_not_found {
            get {
                return ResourceManager.GetString("MKV_Tool_Nix_executable_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MKV Tool Nix neįdiegta..
        /// </summary>
        internal static string MKV_Tool_Nix_is_not_installed {
            get {
                return ResourceManager.GetString("MKV_Tool_Nix_is_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepateikta nei viena komanda..
        /// </summary>
        internal static string No_command {
            get {
                return ResourceManager.GetString("No_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; parinktis turi turėti bent vieną kalbą..
        /// </summary>
        internal static string Option_has_no_language {
            get {
                return ResourceManager.GetString("Option_has_no_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; parikties parametrai turi būti kalbos. Palaikomos kalbos: &apos;Lt&apos;, &apos;En&apos;..
        /// </summary>
        internal static string String_not_language {
            get {
                return ResourceManager.GetString("String_not_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komandos parametras turi būti URL adresas..
        /// </summary>
        internal static string String_not_URL {
            get {
                return ResourceManager.GetString("String_not_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nežinoma komanda. Žinomos komandos: &apos;Add&apos; (&apos;A&apos;), &apos;Create&apos; (&apos;C&apos;), &apos;Extact&apos; (&apos;E&apos;), &apos;Gather&apos; (&apos;G&apos;), &apos;Remove&apos; (&apos;Rem&apos;) ir &apos;Rename&apos; (&apos;Ren&apos;)..
        /// </summary>
        internal static string Unknown_command {
            get {
                return ResourceManager.GetString("Unknown_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nežinoma parinktis. Žinomos parinktys: &apos;Language&apos; (&apos;La&apos;), &apos;Link&apos; (&apos;Li&apos;) ir &apos;Subtitles&apos; (&apos;S&apos;)..
        /// </summary>
        internal static string Unknown_option {
            get {
                return ResourceManager.GetString("Unknown_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL adresas turi būti IMDB svetainės filmo pagrindinio puslapio adresas..
        /// </summary>
        internal static string URL_is_not_IMDB_movie {
            get {
                return ResourceManager.GetString("URL_is_not_IMDB_movie", resourceCulture);
            }
        }
    }
}
