using ImdbParser.Settings;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Win32;
using Moq;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Threading.Tasks;
using static ImdbParser.Commands.CommandId;
using static ImdbParser.IntegrationTests.AssemblySetup;
using static ImdbParser.IntegrationTests.TestsBase;
using static ImdbParser.Messages;
using static NUnit.Framework.Assert;
using static NUnit.Framework.Is;
using static System.Convert;
using static System.Diagnostics.DebuggerBrowsableState;
using static System.IO.File;
using static System.IO.Path;

namespace ImdbParser.IntegrationTests {
    /// <summary>Add command tests.</summary>
    [ExcludeFromCodeCoverage]
    static class AddCommandTests {
        /// <summary>Base 64 encoded <see cref="byte" /> array that represents test MKV file.</summary>
        [DebuggerBrowsable(Never)] const string TestMkvFile = "GkXfo6NChoEBQveBAULygQRC84EIQoKIbWF0cm9za2FCh4EEQoWBAhhTgGcBAAAAAABXphFNm3S8TbuMU6uEFUmpZlOsghADTbuMU6uEFlSua1OsghCRTbuMU6uEHFO7a" +
            "1OsglYPTbuMU6uEElTDZ1OsglYl7E+/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmQIgq17GCUWBNgKNsaWJlYm1sIHYxLjMuOSArIGxpYm1hdHJvc2thIHYxLjUuMldBsG1rdm1lcmdlIHY0MC4wLjAgKCdPbGQgVG93biBSb2FkI" +
            "CsgUG9ueScpIDY0LWJpdESJiEDn0GAAAAAARGGICEMoKo8+TgBzpJB2d+b3IThO5UpCyGVAg+W8FlSua0+krk+h14EBc8WBAoOBAoaIQV9WT1JCSVNjok93Ah5eAXZvcmJpcwAAAAACgLsAAAAAAACAtQEAAAAAALgBA3ZvcmJpczUAAABYaXBoL" +
            "k9yZyBsaWJWb3JiaXMgSSAyMDE4MDMxNiAoTm93IDEwMCUgZmV3ZXIgc2hlbGxzKQEAAAAVAAAAZW5jb2Rlcj1MYXZjNTguMTguMTAwAQV2b3JiaXMlQkNWAQBAAAAkcxgqRqVzFoQQGkJQGeMcQs5r7BlCTBGCHDJMW8slc5AhpKBCiFsogdCQV" +
            "QAAQAAAh0F4FISKQQghhCU9WJKDJz0IIYSIOXgUhGlBCCGEEEIIIYQQQgghhEU5aJKDJ0EIHYTjMDgMg+U4+ByERTlYEIMnQegghA9CuJqDrDkIIYQkNUhQgwY56ByEwiwoioLEMLgWhAQ1KIyC5DDI1IMLQoiag0k1+BqEZ0F4FoRpQQghhCRBS" +
            "JCDBkHIGIRGQViSgwY5uBSEy0GoGoQqOQgfhCA0ZBUAkAAAoKIoiqIoChAasgoAyAAAEEBRFMdxHMmRHMmxHAsIDVkFAAABAAgAAKBIiqRIjuRIkiRZkiVZkiVZkuaJqizLsizLsizLMhAasgoASAAAUFEMRXEUBwgNWQUAZAAACKA4iqVYiqVoi" +
            "ueIjgiEhqwCAIAAAAQAABA0Q1M8R5REz1RV17Zt27Zt27Zt27Zt27ZtW5ZlGQgNWQUAQAAAENJpZqkGiDADGQZCQ1YBAAgAAIARijDEgNCQVQAAQAAAgBhKDqIJrTnfnOOgWQ6aSrE5HZxItXmSm4q5Oeecc87J5pwxzjnnnKKcWQyaCa0555zEo" +
            "FkKmgmtOeecJ7F50JoqrTnnnHHO6WCcEcY555wmrXmQmo21OeecBa1pjppLsTnnnEi5eVKbS7U555xzzjnnnHPOOeec6sXpHJwTzjnnnKi9uZab0MU555xPxunenBDOOeecc84555xzzjnnnCA0ZBUAAAQAQBCGjWHcKQjS52ggRhFiGjLpQffoM" +
            "Akag5xC6tHoaKSUOggllXFSSicIDVkFAAACAEAIIYUUUkghhRRSSCGFFGKIIYYYcsopp6CCSiqpqKKMMssss8wyyyyzzDrsrLMOOwwxxBBDK63EUlNtNdZYa+4555qDtFZaa621UkoppZRSCkJDVgEAIAAABEIGGWSQUUghhRRiiCmnnHIKKqiA0" +
            "JBVAAAgAIAAAAAAT/Ic0REd0REd0REd0REd0fEczxElURIlURIt0zI101NFVXVl15Z1Wbd9W9iFXfd93fd93fh1YViWZVmWZVmWZVmWZVmWZVmWIDRkFQAAAgAAIIQQQkghhRRSSCnGGHPMOegklBAIDVkFAAACAAgAAABwFEdxHMmRHEmyJEvSJ" +
            "M3SLE/zNE8TPVEURdM0VdEVXVE3bVE2ZdM1XVM2XVVWbVeWbVu2dduXZdv3fd/3fd/3fd/3fd/3fV0HQkNWAQASAAA6kiMpkiIpkuM4jiRJQGjIKgBABgBAAACK4iiO4ziSJEmSJWmSZ3mWqJma6ZmeKqpAaMgqAAAQAEAAAAAAAACKpniKqXiKq" +
            "HiO6IiSaJmWqKmaK8qm7Lqu67qu67qu67qu67qu67qu67qu67qu67qu67qu67qu67quC4SGrAIAJAAAdCRHciRHUiRFUiRHcoDQkFUAgAwAgAAAHMMxJEVyLMvSNE/zNE8TPdETPdNTRVd0gdCQVQAAIACAAAAAAAAADMmwFMvRHE0SJdVSLVVTL" +
            "dVSRdVTVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTdM0TRMIDVkJAJABAJAQUy0txpoJiyRi0mqroGMMUuylsUgqZ7W3yjGFGLVeGoeUURB7qSRjikHMLaTQKSat1lRChRSkmGMqFVIOUiA0ZIUAEJoB4HAcQLIsQLIsAAAAAAAAA" +
            "JA0DdA8D7A0DwAAAAAAAAAkTQMsTwM0zwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQNI0QPM8QPM8AAAAAAAAANA8D/A8EfBEEQAAAAAAAAAszwM00QM8UQQAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQNI0QPM8QPM8AAAAAAAAALA8D/BEEdA8EQAAAAAAAAAszwM8UQQ80QMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAABDgAAAQYCEUGrIiAIgTAHBIEiQJkgTNA0iWBU2DpsE0AZJlQdOgaTBNAAAAAAAAAAAAACRNg6ZB0yCKAEnToGnQNIgiAAAAAAAAAAAAAJKmQdOgaRBFgKRp0DRoGkQRAAAAAAAAAAAAAM80I" +
            "YoQRZgmwDNNiCJEEaYJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAABhwAAAIMKEMFBqyIgCIEwBwOIplAQCA4ziWBQAAjuNYFgAAWJYligAAYFmaKAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAACAAAGHAAAAgwoQwUGrISAIgCAHAoimUBx7Es4DiWBSTJsgCWBdA8gKYBRBEACAAAKHAAAAiwQVNicYBCQ1YCAFEAAAbFsSxNE0WSpGmaJ4okSdM8TxRpmud5nmnC8zzPNCGKomiaEEVRNE2YpmmqKjBNVRUAAFDgAAAQYIOmx" +
            "OIAhYasBABCAgAcimJZmuZ5nieKpqmaJEnTPE8URdE0TVNVSZKmeZ4oiqJpmqaqsixN8zxRFEXTVFVVhaZ5niiKommqqurC8zxPFEXRNFXVdeF5nieKomiaquq6EEVRNE3TVE1VdV0giqZpmqqqqq4LRE8UTVNVXdd1geeJommqqqu6LhBN01RVV" +
            "XVdWQaYpmmqquvKMkBVVdV1XVeWAaqqqq7rurIMUFXXdV1ZlmUAruu6sizLAgAADhwAAAKMoJOMKouw0YQLD0ChISsCgCgAAMAYphRTyjAmIaQQGsYkhBRCJiWl0lKqIKRSUikVhFRKKiWjlFJqKVUQUimplApCKiWVUgAA2IEDANiBhVBoyEoAI" +
            "A8AgDBGKcYYc04ipBRjzjknEVKKMeeck0ox5pxzzkkpGXPMOeeklM4555xzUkrmnHPOOSmlc84555yUUkrnnHNOSiklhM5BJ6WU0jnnnBMAAFTgAAAQYKPI5gQjQYWGrAQAUgEADI5jWZrmeaJompYkaZrneZ4omqYmSZrmeZ4niqrJ8zxPFEXRN" +
            "FWV53meKIqiaaoq1xVF0zRNVVVdsiyKpmmaquq6ME3TVFXXdV2Ypmmqquu6LmxbVVXVdWUZtq2qquq6sgxc13Vl2ZaBLLuu7NqyAADwBAcAoAIbVkc4KRoLLDRkJQCQAQBAGIOQQgghZRBCCiGElFIICQAAGHAAAAgwoQwUGrISAEgFAACMsdZaa" +
            "6211kBnrbXWWmutgMxaa6211lprrbXWWmuttdZSa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprrbXWWmuttdZaa6211lprLaWUUkoppZRSSimllFJKKaWUUkoFAPpVOAD4P9iwOsJJ0VhgoSErAYBwAADAGKUYcwxCKaVUCDHmn" +
            "HRUWouxQogx5ySk1FpsxXPOQSghldZiLJ5zDkIpKcVWY1EphFJSSi22WItKoaOSUkqt1ViMMamk1lqLrcZijEkptNRaizEWI2xNqbXYaquxGGNrKi20GGOMxQhfZGwtptpqDcYII1ssLdVaazDGGN1bi6W2mosxPvjaUiwx1lwAAHeDAwBEgo0zr" +
            "CSdFY4GFxqyEgAICQAgEFKKMcYYc84556RSjDnmnHMOQgihVIoxxpxzDkIIIZSMMeaccxBCCCGEUkrGnHMQQgghhJBS6pxzEEIIIYQQSimdcw5CCCGEEEIppYMQQgghhBBKKKWkFEIIIYQQQgippJRCCCGEUkIoIZWUUgghhBBCKSWklFIKIYRSQ" +
            "gihhJRSSimFEEIIpZSSUkoppRJKCSWEElIpKaUUSgghlFJKSimlVEoJoYQSSiklpZRSSiGEEEopBQAAHDgAAAQYQScZVRZhowkXHoBCQ1YCAGQAAJCilFIpLUWCIqUYpBhLRhVzUFqKqHIMUs2pUs4g5iSWiDGElJNUMuYUQgxC6hx1TCkGLZUYQ" +
            "sYYpNhyS6FzDgAAAEEAgICQAAADBAUzAMDgAOFzEHQCBEcbAIAgRGaIRMNCcHhQCRARUwFAYoJCLgBUWFykXVxAlwEu6OKuAyEEIQhBLA6ggAQcnHDDE294wg1O0CkqdSAAAAAAAAwA8AAAkFwAERHRzGFkaGxwdHh8gISIjJAIAAAAAAAXAHwAA" +
            "CQlQERENHMYGRobHB0eHyAhIiMkAQCAAAIAAAAAIIAABAQEAAAAAAACAAAABAQitZyDdW5k4Ym1hEc7gACfgQLsRCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH0O2dWHf54EAo0cYgQAAhgeBYPfOxqjOvwD6tdwuMw/x2jiOpwjXHruWl0tnJz4QbES1x3nd/9DZR1tO0tSekaqKFCEIgPP9n+PfwvMN0ebbcfVXbwUA6L2dPs1nf3VBrbX54GBe19atjV/51s2NbaD33" +
            "iml7jsO7clg6W7I68o6v98553RmNj5/N/v//wmz/////78/n0vncP43jW/r///3YPdGRf5+/n535ue/vz7W5Pbps5PuU8zQz/N0k1QBe3/2zMzee/7/b3sGOOdUnfP7fd1QhfV4f/ddgw7jNfvxbx6lDS2oxnyoZf+/ra6hjbdV0D7lwZ9Sy7hnQ" +
            "cMAtX/A5HjEl+8f+KjG8WcBQBgCfADetXSZ+rzSrOUhj+qyTqg2srWMfPs/Jda0EqJDzEZSqplMzBTr6k51dwl9ieUSo4ZwJUhSJqkCEJt0J1f6r2YQn4FkTu2nJVJ9MJ+6ldTtIT/v3e68fRoZf/1cBvfFKaJfTSZGOdP7+sNdqU6DfKD2UA1Zd" +
            "RMtfZ7TTwJANmjz0rJbPxyc5xqdpoAENhDXdSW/H9kAAJAbX36dGxQKQMGhoEjeoWcfPlAANdPns3L+j4cpci8AjA+463vqMXZVkoX9ZQNQ7zycJ5gASGAGdM0CGW5ehwxkSzAhjJYKCAQgwT+e4CCoj4oKEzkSvrYPqUqVkN74aYBhrEFLA5r7C" +
            "gD02QbIAwDOeBi+tZThKGGFukZUNVcVTgLVlGwtvdr/3cWyO6EmVwAboMbkCumazcj19NOLa0PDsuNQF0DPKOKjBUSc1DCAVRUBIJvu8u/jdPP7+UJ0ZH+XezYnXL6kyQHCxW009LDSRV3J5A58eOv/UTwh49Y5Ot+a5s08rcf7v462PKPRNO2kN" +
            "/q8f7jbsbkDcDNtbDf8WL0KgA1AJqza3w+2b1TVQwEA0Dp5/+m/NgDA6q/HtWmEbSf+vZ1wQBUAzBS/L/Vv6OvAieGNad2l8TxBATptChlExWGwLEIxhjCvLWwA9tv1MUBDohZV5bkphPAI/imiV/1AlEb8ejJA2AvnCPKRCxFHU0fDH4miw9Ci+" +
            "Vsl1gYAfvVUsusDpN8NWSwtrl1LEp4/48hkhOhyzc6XVwAALDsWLfRiqFMSTQ2iSIDA4h0A0G5z8eGTXbtIr1c8RZi5WVF61d7z6uT6qL1Qi/YX22FYIhFNpWl59eT8NzWZUnsQUGgsnixaaADm3rDr/Jp/9169zQydWUUDNOiLXec4ZwHQuTlnt" +
            "pbf+Tp5gImeAFh/OAEAAENCpn1//Y4GDRUg0fUCAABQgEyZb32Y64Wd910ADCTQ+r/XrxEAAACWwo/1+uT1jLgEDAI33wkkwAKgplBgSxSpj0oToDkAAGz7qaSqpQQAvsf2bQQAALpjukcFHAAxAgw+mgJ+tQwyx9uGWUpA0IMaraa4teTJQ6Itt" +
            "aCl4nw714YTg9Fez3/9+/cNGjfgzBObFXoheKhwaEKDUpH2eC+ar0G/eHq1ZeLPsqt5slupu/gO9NKSgzf8WMV1o39GyyqtS8sAkPFc71Cyjq9UB8hkAKBDhm//evM1ozmTPbDbNAAfP50zlDzPQKa3DH3r8tZPgW8O2E0jAFufHIbZguN27sZZP" +
            "D58/G8/VUdQfMBgeKqL0jUAAOQMvxvQZFJxJdQA5FvWCIwMSPrpRAg6WmEIAICk5SPLzPSAaUgbuSdufIwDGiDz1eNrACDTAQBAPv3XNAwCsP/qfwUgEHC6BGCHD4B9BkC5ZxugAZ61VDP7GzdGwRDHydLGryWBDsmyjBkEyfkS15i8QP4AAPgYC" +
            "wDf/nYBcMYsxmgYag3Fqgoge2++NgeemlJDm3vAOS8GtMbqPnDmIehV8xUEAACkn93iJbN2/YMvp0x18tGVjF2ZFtz3kepAh94z0IHWSj5/zdnvOINxA2C/L68ftn27FwoAGcTA8PXTA6DaJq3PVQPdyTTokMlQ+JVHsrMwYDXGiKw+jNwOZ/YPw" +
            "LjN288vj9r+rEiDak43bTYrMRgAAMzPasAUbAfT67o4ON1RIlTlL0BhaAAsmxfbPe0QQYfK+OJFHF3xyu0VafVLg5DdxmPNFjfsN/iDiMkPHUuFb2RDFcABfrZE6v4DZwSkCGNZpQYkbImJVTKYeiCoSg3ICgCA17xZAFz/nwc/AOpYlFSqKiZTV" +
            "REAS/sxAI30qBBg4dezHeC9cSMFQAgQAAJZWIumgdqjJa0+sl/37TtvB+tjp2Snurdff1prTWLb2eqXwGSYdt2dJAAZjQUApI1QOmQouQAGYMZ6zBoabSGR4sKAKagpAMDPdQEMAGalVPV4ANUeW5u0Gv6Z5MhvSi+HGQLtxyvJtUAYFmZMo4XSH" +
            "d4TZJtrur4Hk2pV2g+AZMA2jgKAUBEYIa1Y61cHuVHLOcE3GXEoUL+Q7syHwg/1rOvpdvA6CG07AKNIOoEagIYHQQC7zb2zzM1+tQxy61eGMwemzEsNSNeS5FaJRp0xtFFkaWmNyQv43A0AwDusBcDJzzcGRlRomiRkElekKgKQc76Q1z+fnzxK/" +
            "y2Adr8oAX+ONigQMlOe9gnoSvPNe5SiIcvufcPz7a++/XVJKQu2Hd2vCoAMAPTeKAAAYue3f65zwPRrMmHy0s9HSBVAA2fwRA/ajErFDJVB0TfDtLmc19vZHMXiaQ3aMlEA8WffUQ49PYWC54+j0ZR28aPm5CZjzWwKVOrTe1sMDhCg0GC8sssSV" +
            "9/tEeMAZFQjPTwyHw6uvVxFt1wfpAy0ltnpA3co5gPxDQblxoUAf2K2S8cdOqkrWlCDIdgAXrbk+PVvZ+jGEzPULKEGJGtJkus3YUgIKtQQ+QL6+HVob32Dzyr/2yX2rQAOnEGlGTRJaiipqggA7BzTGx5mHmeMSIUc+v+bIIPb/sV2pfVQgmcxJ" +
            "/+RAgqQcy+FlmLOjf93Y29NubBomQZAhk3ts99zA9Nc5MsZgMz/z2Hv8wzgvW8HJweAGWx+n2T5NH2Lhmno5tYYO+MCc+/b+Ti3nP16JlMQWPu5mCp2DvVi0vnWBqVS9TMlBSwIREp+rwhcQjXJtzRoghALFhhQwwfG3v+LzgDfYy2+LqqqUIoGL" +
            "f6/s2UD9R1y4RkZoqYdjUL8LuyGYUNcW+8PTBUAXrVU8u1OOKOgyUA0di0VfpcwpqMYkrNEDZMVAAAvDflNAOZe77PRrgGqZKQqWUlVFQLady3gES+PRzd1pCkZem0B0G3kEIDea7fyRdnjk//eOvLbB9xOMP/ixqVXVVsBcXOkj275+22aj/dc/" +
            "t3nsT8N4zC2fc7Iefhm9/c5N3u9758+bgDI9Z9rubAp85z/DfhgGgXWnMkbMKzPJ18GMrOgn0WjNDdgejZ+pMK5Rw6cAib98VOd3VA9tTQzuFNaG36B3Njd6jOdABatdlOnKJrxFV+LSoIUFEqJPJ92gtJeriVt8dwIiW6no496O5A7gNssqjrZ0" +
            "vTQGih7N+Rj122p2429FRcDTAPetVSCRaI701CajDozOoctITlJBkEEGZiGF/A9FwDAa/Z1C5izvjmlwaAWUi5ZCEJVBV9YDpPnHYyPfrVvAsvjBvzopls0UGsHtdxYVig8/DT/2vzpAttGdIYdTIazLmfom3/5XLoL9NwztCwyBbjxbNg7dAKnt" +
            "g1tmrKa7H3GENOdje+a1w8auHWcZ2gUrHHbxt6Qj9fmKLgs224+3s4d+fuzB7oPMAz9jmFztv2+z3SOaxCAqvpVMf17+HWm83MCAI0zvg4Ja/Z/KZIqklQ6WAHQCliCkuqGogL4IoLYAjAYvWh9IzsCG1tAG0NAENBMa2y6HRVhK3Do6Cy9G2hAc" +
            "/XDeQd0BADetbTURZJsgYSplhqQryUgZskGAwyZiMYr+IRx2ej91/x7B97p5h/vAKyrn24M7E7TRYIbKqQqhKDk0MX+t5fTSUvr5cvc7/VlF1oeFk/KGwD8ruNGKATdvnDngijyAgEAZHcCOg0BufecvxlK6+TWS1vcHekN4DG/utjGGPcbA8O5z" +
            "+X9/50ImBQFT4+PY6Ki6tKYTmCYeW6uhAZArSqTPcz05ExXAs0A79wMZ/zwYapDBTPMbwWqgOwXG0DYW0BoEPZprRNlIwDYlwwA9frTC/vlqhkk1u7CQ2SOqif0HteuvoN7qjsGdRZW9DnfAPEm606M0x0EsLe3CAB+tcwEy8ebomKoz/lryYNZQ" +
            "jsVMGRuGq6wvUfqXW8e8/8eQPTXe7y98w6Az2/O0mBQFlI1WFVVgOInA+Hi3WnjMsf8/7471/s5JPYP8lKwIYP/oZeRz/MwgBwvrcm5z3e93S4wNaZG73SA1ll886gMFBqLq+QOABDmMDX3qTNN45hyO/ePPWlJ6r2Cept68bOoec6Z95G5337Oj" +
            "VjV0q8l53tacmqaVArTlA0J6jrtiHNmcfwvMs/Z1hPOFwCpNh20gtk7GufbXT0jjd9lgkGV+Fmr3b8mAEBgm0jbSNbAnlKw3PB3p3CMQvhAOpDffKRxAn601dk3DjhvEFq6tcFq9bX+Hm3ja4A3nvVU7PYRbqiqo1aja8mh6W+bIYnIyNLGF7jVF" +
            "QCA13t88+c9AOLnM0bJxIQyk0RXVQ6l7OD/zpedTkwlGgI8tYB8vT68AJR4xlCAvHXdkgkOtkqnw2lb9vJtm4aJ2+32aw29Hzzd4PVMRrRMbnKhZ+p/8Lc4iNMRHEztYajb+ygGU+b2+f77w797HlOpc3u4j3s6yRTVPrzzfLxNxbR3xnx4iLIZC" +
            "qAqwZX3Nc2NGzxAkZNk3l27upRKBHXl7rrffGkk5hYfG8iADBL2IkDAbQuw9xD2ELeRdEtgCSQkDMdXpfoqVVHUZmTGKAIQFuZrSRIRgCSJ2waAUwApJQJN4RCMAUFaBkcgbxkKASSvU7Of6VYXaGIFXrXMhdM9pqHHlIOcu5YEMUmYwYCklpTyF" +
            "e72I3rXUjN/2n8DsW4PJjwvuKFESdNioV5tqqpQVGSk7xsPnxreRq46cb8zrLNzyOs40fYF55e9gBfJXR7ZKHhK+a+Nx5QM5eMMnVyAghc3zeM2tjGn3F6MBgaI48gJbDX2469xOPfzuicZ6MzKPl8bbclj9nqSkE5oegr+T6MBvOeQbTRqGAaM6" +
            "YrYz7A0T4xV+4iYnTmzu4C3l+a6v40+nHjsRnV3HNIJAtIFaPBcIAgGA6EIZCIVKUqtpqrjv3UazemB3YqPAAGK0IE4C/YWICgNWmt0zygqbdPvsGnQlLC5gw0Pmml1AKNIM4E6gYYHQRCpv8vAs9C+tVTt+a8aqNjK1IhkLXlieZtwRAzV1Jhcw" +
            "edLXOLwxYvRQFx8VsE3c0BdklESTnA1VFUFH3ph7WVzwsain78T+XwZ6iTjPKjU3pt7Q/duK9mTl6KDg4wQyBmAMuR2z7GZmBbr9w6Z/pfB5IJGKeRAuYrJe5PAfL7cx9lGPr15gISaInq8TjLNqUrO1KqmzU/6WqlSJs6c8z+xuWDAZBW176Me1" +
            "r33p2E83mvcGQrmYvfAm1z9JF1J62TXOtRsAyChvzlzaIQ5oNdggzAOBVsCxXC8sH6B0fdIszHtl9TL9aNcPFACGD8GAODbeM1swpD15yhZtMANJx2xqrEjnnFBQyYXpmitzhQD6ww4YFZgA162ROr0A6WACKvSkLakdJEoYVQIv5qU80QPmzX/n" +
            "Zs5ZNxFFXQ+O6JpWkL5UEhVvgYaa6vsuSrKveH+5T8NlKAg9sWhl/Xxcljt3Xcf+pXB0R/VgVZKz9CmpOpdHJSv2wXQYS60DMBEfvCnowXQO6rpZaYA2ZefYw72OXkdoDgDdBwtUop733rSuN/Y11LjYegiGdN5NxeLrcb1XuEFNONd1uoDRm+PR" +
            "G4qEVy17yC4Y+dCgg0IbKQLIzn0IS90voPSifCm/V6LuP/5PYxKkJL31O8fBVAAYoNvW2l1wT9RAmgT2Ar8/EQBCdBo7rCHCqhCoy4bgDOhbTaetQzC8a8oKqjlvLXkwPjJEGRQ4XxFZgdHlwzN8emP0OTzrVjBQzduKBGVpmJSybCTkKoCOSaP0" +
            "UY46offattMiLnnaziVebFNLY2cWnIIffWUlHnx0FYPN4095OJzXCmYTIZM72q5FBp0yjln//fJewTAZtkDwPB1YNwfnaGogeI5T0azVfKO4aSWatdBGwGX5fh+AMA7XeTNgZxCY1vUq8TW/Lu/nU2rrQlAR4gm2SgEyk+qlJIzYnBVgKyia4oqy" +
            "DKpihEAoDcwtsfWAij1lt6IiZARsgHcd0ZQ/m4BQBEIAdiJ9IDSbm1KB8kqilE+rcp20EnfuPMQnvW0MuNdUXQY6kPZEsL+lzguCLWWxivoF4wOjyd/nIP9qs9v/SsA8dz2JWlaUslAiamq+JL1tK0f3P+c/Cf79jFtD2nkeK+hoj/tnpPF3IntE" +
            "iBoEkgmDsIc//9f23sYRW9uMDVaJnn+V9QcjPnnuodhK2Bz/WoGbirnXjoN2tQW9RezyAIKAIIY0rAWJIio3wKAmuHQGhjaVic/d9E0kDQgz3QZpqXkd9BuaHLA7doocKSCqL+bxYf0soFOd2VRwFRn3bqjX89RVNqg9CAtuUDU/9IqAED2ItlAq" +
            "W+KIhUgZLgNAAAyehkKAxwAhQ2NpiDKrODRFJhvgbbrG5Bd35h9aGAfBH625PhZwqpAxQ4/A9GYtVTJ+WPC0WHKKDReQTJ6NHr/53YDmRcPNvDu0mnKDEmsqqoKJS394v2Z8TZoHvXa/88uM0jDE1orD/3mG9I+ne9n8ZeW13+nyW2D1ZME8vat1" +
            "wwyA+Q9cLZp2p+++V9dTbH7iZlDw3bG3DNez9OfexqOw3i9zYz3TyV0gg8pdvKPjVLHzQzppHKefmfdYpHYYHLHrX+AfEYf5wUIKgaAvrx5//fd54XdQ2NsVgAA9oj10hqqAqnnyvtbW7NV1eio9wjvf7LZK7gr3UUb08ZC10yr2/RRE/ToW7S3y" +
            "DZmIO8M0qlXfAIi6OAsSjZCYCOKwQYMQwtQdiYIfvZEXPtJDBk71DJcLS1+uiuMiqRCivmBa2/4rmFu28B/44XSoBlUklC7qmqF0urYba4tVJ/Z7l0dp73e5eT8pr2zNpKP6aejcu7E7YqZQ9vvF3nagFJklm8mAz6Ex0qmMQEFWupWpvfSaEaLo" +
            "j+5VoDJ3WFSDNwkA+ev2zb2GCaHs5ccTjxYq4Me5aIBGJocsuhrUVOVHhZG3fPfMIfNKI03QGo2Odz2bAdTFaCqfQ8SNmAAA/qyLRGg2BrrgDHNC35mrbW7LUApLh9XQGjABgM4w+vXtoIe3vcv2gFoO+pv2DAk+BmwaA32HA7bulRBmmz9DCBPC" +
            "lGgyRWe5bSC/gSMiq2E0tiSQ/0rmiIqhL1szHnidmlbT9/o8PR68cdsOtDX4x49GUkoITNcVQkizDLbjMFdfQr7Tulo9d/fzOJtHMBmvWmrSJ7ylT1/uRwrGOMRefXLQKnfGjYrN8gF52ZwjHHvPsy94e3x4d8CbC/szSb3bcDMkfYfK8dVThnoS" +
            "ir7bUNxM0Wizr5fNlkFw/wZlh5a9WtNZ/H1vifOehygqQKaiSimFNWeqebKRGoBZABbv8DmXDSbVPul3Ba497OAAQDLr4CRvCXhF9VGkFeRLyGEJABoCN3jZbYBALxOQcYBadoaKEOFBgZaPgsiZ+F4OAzDcb8j+DSQfwawEbRHAgYAwWsbvvUM+" +
            "fknmqDDVotS2ZIjx7+XI4pB+JmdlBonCnuu/1YHO15dNRcffgDg5ike0GQjGUVSMY+FqqqGZ7a5a4s/L9e/3h+ezT8csCVJS/EUCFDC6rBQFiWSyhq47uBXrU9R8WPTOCGh3O+xufcuFs978nY8NDBb5VMApHIpNeDeNRyUsh/6/b/fF0o3TtNjA" +
            "0o+B3g/0ENRNMyu5QmPQgGYMefrfNuD6elemC7OzoR3unpi/1DqNqwenXR2Ijk+SpWoKlVJ8vFY1csWCJYRQP9WOvPjdbQgd4XDjpbrX1q7AIEMFgD41VFZAACgWBiQEXuVMmiDjTalZaSxZRv2Gprb7HZQ1mcy9KHhRLgAm5QNo0g+gVqBhgdBA" +
            "Mi+xLHJvl62VLnxSwSiYEdYVW7sWpJE/yQNdNgu0YibzPEh+N+043sN4PJqL42kaYJUsVhVnZp77bLbuLxEHghlevCkcsb/W4WCdd0Uun1497efdOtiT/fur/hQ2kwvDZjpZ2NlSjs4P/4SMiBzs0VYX95/HHYAJvNSMzQgiVSNxTznMCdzut3uK" +
            "+abVb+i9P1TI/5bgs5i7jeiM5VNPWsDolalaVKp3leTMI97ATy3a6qKogTJsr2hCQAIXssymIACJJ7+V5WdUbirh73DZhuN1WG/n6MRnEesVu9AT2e9XXdDAwNf93WdKmw2dR+uMUbFwaVpgdaayQpGi4XAVqNOYQherQBe9uTIKqFxJXY4odZC1" +
            "1JRJomgyKDCeeIQwvHkqQnm+jrgWnZjoWmSVJkJVQmtt3bSmNyfkj1yn+xUgx+zWedVqm4nXYdODr/7nZbI6v+fX22fpZ0zUF3o/NYM5On9clmnk4todoHQdO7PGW0dUFtvvU30omny5uvm+PehFgOYwyK3q5EUikurATy2Lg3o9HUVA5M5z+r5D" +
            "6D0lMF0fiKhmuyutHxobGFPiRbPnguek2KgCFFV6Y1kciNUpVJV9c7kMwjiwbyGHrSjY+4eppzOFEeyAZ5FttG05a5jWyDZkjBvxn87KPz7MLqjX/swshUamyaKGATwI34GaRESAAiLS62dwFaEb7QPfuUM7PZ2GD2mMpJlS4Jv/1BFLwThV2vni" +
            "XNC9q+2AXfTAu/pjYxoAtIaDhWSIIhj29mXv/fM+bCic/76OgVkyad6cHkJzpvFupY6/nefuc//XK1+u8w0MoZG/vmglUzjbWdRKY1ScgNEJnf387c+JtvNXMz/OAD4VzSZzcw+zD3Y2/OPt3lj6Hae9hEuRM8GPJX1vwZyXAkZV5EAAM1NdwuHg" +
            "I5adQRldQiauUm72kDsCQAAIMUWdW8kTtot0Em+xkaMqJD3RFJYUetHdoQACECkvkkFBJ5CSb4JRRS7bmjjPtFmQk9cHholI5shAyIMFchfR0FoAQkARBOweSGUDQAqAIAMaAUDnuXM2LOE1QS9aCipSl1LXqkSCgwVVDjPhS+Ji1MF0O4GzUiCV" +
            "KIQpIoUWy82L3zUcJOT0hbNu6dLf4/+J3i07Qe5tbRAzamB5f+IPf19Dz9Pw73WejCN+xhj/M+Zztvi7eX+HNskQyugIhYl//MyZ4Di1LNnABuejfvYHvq5T3OY5jnn/dfb3PeBg3v3Bw/DNvMkNDCH5WtswdqVqLczf/vubeCYk6FEDTw9DEyz5" +
            "7zs6SWhHnICAAJWKZbq4JASCb+kjIKBCZ9ukHWTOgdJigUAIIX4lmUwDw6+VhaSQIFiugdcvkEQCrze0pCUfA2QC7QVjxlhez4bUOps6HTWohsBMaL78YZjHXoAvQG+tcwEXcLZAguOWhrKlgQxfdEAyQ4/AY0P1Hf2Kj6aXPv0RjKSJFSrqiooE" +
            "3ec/GGrTz3+vHDx+FU/Shh+/cyh15Jd98VXxsm/rf+wzmT1ej72yvt63Oa+O4qbtaCPf37NhwIdZpgB5wa5e357BoPlbT3uAKYOUU9R98NGJtMej+d9XNZaOyyZzuj4dBcjphkopnTqrd5pC4y6b87HIrNqSuYYpk2SoKcbPmJwd5/n0EQcnQoUe" +
            "SqhLgGwAWz5CcVRSAdC7CAbYo1vlsIYM4tQMlSi5FcKaDI9bAs4TGPCAy2mEVMkadrBfK6RD7OCDa2BTSxmIij8EDC0EBeMOwO+tcxa/e8t0OGWSXJD2ZIn9p83R8YMv0zjxDF6ztd+GQH66973vwbQmMe4oIbRkzIJkmMeqqp6Of3ah58CFYyd/" +
            "ceY/V/y5en5IRBKKAkyBrSPB+c8XzdHT06Yur7T7+fnnvNeHNOR68Y4GQbktfO55oZxvtwZYI7zdWHje//T7Qxg7Pn46/xbnGpIGJ7NFAzfGaB25fxj4BSY7nx9G2P5xxQWoFcHFqWUXiiNmQSqq3LuclWeG5z55ttNXsW2BUhGVhB+EtjPRYKql" +
            "KqhpS4A6hugoS8VoU+AplUArVgAAEQ2O2rUov4utE1uTEViaEa1gM32HmJI22zCCoADaii8AVszqtA8mnYBXrZUyfEvIlFxwq/QWLYk0HxP6ojYEdbSOHFlIp9mAxq3CpTtaBRGJwnxVFVVSH1MreTFNKF987az30sMpLmtcikzByi5Vp/SfeuPf" +
            "P568dsR/tLXFMiNQtmMay3HfHh7yTTG0YUg5wYTW3/jRwfT49u3jD0Os77+raYZ84wZ9zmZ9h9X9/83WemONyBOvVADwDlvD+Zk3OZZbaAGcga79rnPj4ebbRT2mKY5RHwBOWzY/13Z176ORCMBlVT/9We9lbSVK8kBRrYw+hfMaUCabLTLBnHWA" +
            "IIPGACAEWPuhxyKLDaTnHjlyKAHOKTvXJhuXi+hsQUbLYkDHATHvTMEFXCSAyE77SsCXrZUuXY3lQg4EWYUGsuWCli+thIVJ/xqmjxguqhoAuu+L+GEe0QxahKkEqGKVQXtmSVdYnV8vrTpUPvrWaYc/WDCffGEbdi+njjx+W/PqLala4N/sgdbD" +
            "G2aZE6kDmXxOn9aA7TGPZMN09zXRnvbNkf/ZwD262jO2DX6y2qaJiHNTC0dVr1rLJ0wuV59D+BeO3Mp9ALk/KHbACrVaVs7az6eWpMkFHCAN2m6iM/cPx1yX8cHAAAs7CtkrUAIhVp8NKoIbKpK3u0u70IDMMi2FgHCCJsHAPUbSKRg4RUM5/2FK" +
            "ydn1Duy1uAcIqZRaQHIe7ArQTVAXRS2QWgG6fgHGliHKKNCCoF6goYBQQFetuS5/jU4FuzwSzRMLfPqsgsPdIrjkkTjA74Bf+B1k2+/+o4A+Hh2djoisYRNQhVSISK4J+Syd8xtYvd+ujy16poPcze2hWaGov9WTv7knPMJy8Sf9zOMOe1p3tdD0" +
            "NZvw9+kQ2kU6Dm7Az1vLm/+pWQAsp7uSnUAzo+xy83+dPUiDQagCKLwCwAAIB/Gnd07+7UZ2Y+DoWkQcX8wF4UhXGTSBBa42VQCMFBPqaY4ro46Y1sPEQQV8SuI6RAO+n6nAMqnV/gbECDMhY2YUR+KQUT4WQEtvVy7IWwHYEAh2EQMa2n1Wpwwe" +
            "DCBBvfL3At8PjQEsIQMB3VsD3AdUI1uAd61DNVRQlAs2Ko5Zy0Ddb6LCHSYcpgmDzb3yfjhvca6+1cw0PuNhNHodBSsBBerIg0BSjc7fJnz49XIerbUpy5vox/zdT10XSzWs9caIaydH4hjCeD3x1+9DnLJ+RPWJUMu0JU36bmQEVAWtPCbrdsb0" +
            "7F4+PjJGBieb68mav7j2BgOtyff88YqzbZ5HHpHMKdKqguysbs7igdjeO6iKdYDVYYDFAlA0ZWRqpqqZMXY3MIAIALztmzUt+ibNPAMXdZpB0CAZUvyys6RC5wn8L7e5WmLrujgmBs1pv+hvtDVa++kfguEoYUXsE0GOjEb0MZfq8NpU7Fh2wYFM" +
            "ACA0P+EPh9DtnVPwueCgoKjSGmBAACGB0EWsrvAyrnDvrXMqstDJCKGHKRJ2ZJk4z95YMEJm23T+GCPcwLlUuBwXxYAYI/GyCQJiVAJVRWChlANvn5YqzfPp+7O8N1riTmk87nGMtcfLDcJgGFbPr/XmZjdaOdzhWxB3bNA1+Yckbizlzbns9/7v" +
            "d6B3CfO3oycc3a1f5/BYaz7L/zANKgmH/eHKffzxh4Hs44/Px7jcFTNbrc9h+WtH4PMMeY4Yzhnl5nV+0y4AAQ7azy8vNytrmOKDeBdUHOuMcVMnbX783lb55AuJUJJfE2EWPWAJAuDsFcb8Axfsy22QQDYRj+sF7AcGACyOaviIDmk3CllW6IGA" +
            "DAWFzJa2EwPC65aC0g3qKyb0AGIqkMhE8yCB82hAQFmwQFetrS4UULZEgk71OyHxrKlApY/HugwQ62mcf7kxb7ivX/6PpgDeyxR0oUgJYoYq6ruSGXE/Hq3lqbCzulgrqutfjg/kJc/wPpmfWC6ceXBXa9/P/Fb7y3PvIgZMoUxOn9dve2j7Afzz" +
            "tz22bI7y1IAOh5YPosOaPCHonL1CbqBhi44wZMKYGiT0BVdI7LHBA8id3nQzMQ828b+EZpOzn9e981b52Fac48Lug1pzxtjfrebl0bNfYkACAz6LuNCGlkIVeqjEr6K4HRuB28bDIA+MhgjFEsAYBUlPkohJOA2bE5GGVWIDsfrDS49LQf7hv2G1" +
            "xXCaJQtg+JAQwegIRwaGwUMNGGrR85rPrYMyOktWyCjhV9LQ9mShONbeqDHibBC4wMeOLdQqLlf7zj593/qYM31aEfvDIakcizGXFVy8ar4e1u3+bV3tnt2tle5/kuWMULn3ebbxVFHtQ72lA6/Chjc1fX7hlvPT5W5596DPlEyBWgeR38u4NR8+" +
            "jWYhp16uj/gdb6/NcZgbCdz/UxvyDkn+4ZHGIPt3OYYNbz7n8lJqhh8sYvqL1rRnzPj3/EwjLHPbU+AD0VmwO3qzFNv295ZM/zYRYWilCqpR/+XUNgIztQPrsDQQvo9QDPdS2kKTf8jFQbWjfhiBxDaKID68yShhZCAS6LvAXdkmwAgBggAodERb" +
            "YA7agZaWhMAXrZUuPYx7qg44VdzLluSXH/bClTc4WcKTeY4VM3zHc34//sCIPbSKHQShMFcVVU5mzJl4+tvbkJ/PGm6Sq+NVT8rOZU9B0hWrKnPn/neF5vKF/O7DKWkXCi9aFOAttn7X2+UTKMZu8xDML/m8UbrgDpnUwM3zb5jVc0aXPGaAcbw9" +
            "Pr8qGHVZlT38FUeJVBl7/vD2HPIyVt+KcfqN1E08dwPd8wQr3Ga2dTJqssJSZFNwlfxv5Ta9YwBZHCIH8s1wNgSaBWygKqwP/vGIMCAAfbpMErB0NyJjZrZl4tyLeaU1u8Ixus5hswRzDJlmqsbzzV8hpidTQPYKM01baZBO6jCpm8DCl62tMnpx" +
            "yx0Qj7hZwmNXUuVmz5JJDpMFZq+gHt2AQCWGz+M3hmFIBUTqqriGU8yV64T5kN+bD8BXA4ABC+1QSfNAiHA/s/k1ORqa5f6jmFZEU2Kt9Nbl3uqB+M2jYPxevN6ey2ffnZ5CvbVAAG5MPfy6A1vG4y8cDgM9kMl265RXwDDVn/s11/nAAzTQ/F2H" +
            "/vs28eczjiP4141Q8K0kqi+6ruBAbjof7KYM8f/j2KSBLpfV41zNhZe3e4/LVLFDAAY4AotmkOLFJXKQ72cfLpz4OZt4wdNr2BXoGFVQcL5tQGD/UcIYDTqxjpnoH+YettYudBcQTQfJd8uN2JNbtft2hEBt6UpjU0KMA5gjC47Bj62VPn6IQILT" +
            "ugsxLlsyfHjJzzwwIwwi6kxmXi0g/UmIZrLS/GhABcMLD3pJEkJrqqqJvrfd16uD8Gnd72Zx3HQ7W97vbG77P0XQH8qvviJAIiHrkMz/c2j//f1RtjfuXi/P/q0uF3mmLe9hb2pzbm/Pqz/3uQCuC+UfO7AZFkgYPeyYhq1hYuv99sqQAuKopaeH" +
            "vqQl4Dmr8+WKGIKZXU++1OwdcUTzDwAze+dpkRB503WVA/gya8CvKpDKS0CqfyofKQQDaWUpFIvJFrYOD5/6g0AAKBHgMyqNGjd1pGh57WdXJb1RmM4Ahxq6ARf64eK+yRxFgPEyBKkCUoQsoATA6iIrkEA3rsUAF62VPkqoS1Hhx1qfc5by9Cev" +
            "9oDHbaMTJMH1yPPnnuTq8D17hkfP2sA5nsdN+weY9BwQkMJVaQCWdGjv5GDxnlbw+p8/h5YiYWb9iVnv3dwcEfu/58GPEHPBjruXx4/lcmhwPMh9K4MBRPmgiQRahxEz9QBWuMbv28ExFjsBdMenm5w7HNqd/6uSQEANNQrUlRHNFkjzaaRC7kUz" +
            "jZcLTPjo/nRUxO3z2Oif4zbxw5j1OdtVLqz89W9X945c705QQaQ/SYZGt0hssEWPHKosxkKy9gAI5m2i32QsfXNBmCrKxBG6VBQb0QjwGMjQBgRCrgd2ZfI3gGNHmj1DU0KYMCZTg+NvUsFFwAyTUbW5F9etrTIUULjjg471Pqcy5Y8mn8mAhk7/" +
            "ExN48S9CVfrDyCPrx99983/zAeQ4/FGA6VHDJogVVVVHY23vbAXGsjxhaxvHZNDQmWbVLyG4hf9XS0hUAKA6xv1/Sp/yehrnu8ZzjzjgOGspHVQAzKL5Nlf4qKBznqXP80kdb46jLn3r2HcNhyZ/sUAWTVA36uT4soWc6bn3cNqe1XW2XzcGQPOO" +
            "IvPawrnw3CMVlOP3Ud13prkoXTNuZQiCAAbL9j2icsVTSmV5N0Dwotv5R21ugrRi97atFJYVzwcB7lvje/nPkQqklnv84pY6rY5Oe81YmvYJ7nhGk2Nmx3SAHZk4MAgohRBAzkCAKNHT4EgAYYGQRGwvMm7v162tLnxI6uwYEdYprFsaXHrW3sgC" +
            "2aEJ0uTKzh9s4uFv3akdfN6x83/f6YBGuuC00GPSjJIUrnMqqrQx8wajszf3Wc3lnaPRCcS5n4S9tTm9h0tn/emaN8aefD59fFnHqBo/+HBdED8tofJmbZz5vuPL5+Z2Jdfv+Z4IKtb6wGGb2lnQ8IAO75zryrAYSo0+iihuwZmvTFN813scZRUv" +
            "BMAgbZORCOdzPWOEnocedmDsvC1f3X2uL8+PD485+IagfpFaZOvXAhJVKXWtVRK0E2gPWjG/cSJLh0CZldV+hZwHLrNVwCAwXCD8CU2rOep3jB/g96vMah3Dt7xM2Cw45sx0Mh1RxT2JjQg/EGWsy5kAj62tPi2W3UsGOFnFPVctiT59lYNPHAiL" +
            "tF4Lh6q4evZjWTQpBpyrkKq1t/PP/8bn25LWwRerkBppmVGJqbSqeGeV/ql7tk5D/7/703j3JD23b9Mbhx70q4WyGz939cOFCDTMq1TaDk3vNm8FzI9907sj2eQC84N0x7+67c27FuNPT9eWpfS8W670rSYzetJSKbez5mEbchk1YCajhX+ubk/r" +
            "XHYect2aGj+DAO9iePaPfMEEGxTApWm/beqonDo0pHhFEsyUKeGHWJcHEDYMYABGhNPm5WeuKTnbPLuACCUVmMWCYg7smfXlYNjeNqv66BDxTQEtlHabpKlDtIEGEHIY561HAj6QzmiYLsgK5+rlhl12qU6emzVNHlAJizeV8MvXx5gbszFOpQ9K" +
            "WmCVMxVVSQQVFb3X67dzPTK1/xKlsHyPY4/tC97xDYcX/jmsbROvUPy6SxIOruG622U3B9+mvp2L5kCqdYAeoPWz/c8dqHxT78vvbFOMZ6Bord5YzDOuM0P30+Jru4smupIDKbhLY6hjqdMjZN2/ssBC92qLJRsZaLn7A+5TzilEK01mIKBh/ieb" +
            "oqAEcANtjFFIKVUlN4KgSooDEuBr5ubHxGCdigC1mkm+Ff1OqfKOmxAxEcGC61u7D7XhtFtRBEUDKcGCHsboNh3seh7O8n8eqBpA362tK3p7x7oDTPUqjScLUl+/jThWLFDzdY0Oa+N579/NoBO86AzAOpsZNKYVJuKVfW11luTLEfO370Dbajsz" +
            "yEZtEDxAYIHWla6V0CuQSru0df5v7tXUSEcL9/5oNb2/C+fKwtS2n7+38MtN49jMsfNj4cGfKakAQB4Hhc1xLBrUueo+dZ/N3UTByFn0p7MYmic3V9l8Slthma514aEzqGLC3LyRJ/wJt1dS4BEjSahBObpfzagIVedYw4i4sFUM5KQUo/5GoEmJ" +
            "LtNdsRg3DNmi7e35SH1MwWRKpf5knYY1e32al7J2dhVxZ0KfCCNwoKtQDzClStu8AIZKDSd6dgH9RoQ8u0dsiq+tczY/SMoRBQJqCkpW6po+YYHHpjhV6XJA041Kjo1FF6Ppl//l3N0sC9oYOlJ0yQpXElVVaCXQ/lPTjdeHOWfg9qt7hjm1q8E0" +
            "nj6s+O0SZ1A6AS1yxYgRKNvTlHICn8W58HOtqevs+bZhzLv9uh5NQMUIEx+oAGksqJ/Fd39vw8bcDw/HoACILOuPQCeYYBzfN3QCTRvOFU4+kqD1ZPziZnKhDdMdNWNSv5Iz6Z7IPKeC1wQIkRUvvSmQtgNCaXKR0JbTIx86Z/LRxCAuAz4gAgLm" +
            "9xKJewBOzzZASoglbwXwARKA5yZ+P/RiOQzm7ABNYG9IebWAcF8/h5aQ5AYEjD3dgB+tuT5/pcQMnb4GQEpyLKngpa7DGNZRSK8KCvlvPZ8vP5xNhtYMUomTVVxyKuqqiY/Gvkxh+zJ46EXDZy+yq54v27ajj/dtaN63I4ri/3735M6vzHXDi4+H" +
            "g1nMPc4sz8uvO76x///nDsDY97ZZw8sxsNvtU4lXfkuq4oaYzLO9znn7fbbKQCgm9ph1FkwWQAi13m6ybp3c5X5ui4fNk1RmfNMQVtpLtAU90dz/LyA0mCEpNlwkltes8mB3p9HjszaCsmGBGaPI06MZB0tELYXW5JdPl/ZsaJLML1soXxRogK0L" +
            "XlVKAp8huYoAMwuUQBpwAZyY65B8sghEj3OBYKyzWYbQAH+tRTpKjFbyCur3l7aux6LXcviFokqES85vCWna+P86S8ejqtav3uTkFmSprGqhqoi9Pb2b3xtXPH+8Np8tfdZ4tJnzzjcvice3i271e4kCLTeNOTq+VHa5Z0Xc+p9sjRfn8P++nTl2" +
            "V3ffv58/6t2D0wP0JYrCvsKl/Ey9HTtM1n0wD4554o778hk5XR6mVrW5u31uN92jfvba91eP9TrYqK4rzs5u5meTve+NWcXh/8e3+/+qVdnac7l3rfmpF/NZV8mkDjd6WWXptO964d6zYT+Hc8hLF/seeLj7GzvtA7Qgn2x8DBw+rKYmlhJLV+t+" +
            "pWyH1b9es7QruuxsCyQZctNPZs9X9cVyqR8ZgCMAxpiexaenVre06cCIQMgHFO7a5G7j7OBALeK94EB8YIkYvCBAxJUw2dBe3NzQXdjwJBoyoEyY8WBAmPKhU1PVklFZ8iURaODQlBTRIeFOTkyNTVEeoNlbmdnyKZFo4hEVVJBVElPTkSHkjAwO" +
            "jAwOjAxLjAxNTk5NzQ3MkR6g2VuZ2fInkWjkE5VTUJFUl9PRl9GUkFNRVNEh4I0OUR6g2VuZ2fIoEWjj05VTUJFUl9PRl9CWVRFU0SHhTEyNTkzRHqDZW5nZ8jTRaOXX1NUQVRJU1RJQ1NfV1JJVElOR19BUFBEh7Bta3ZtZXJnZSB2NDAuMC4wI" +
            "CgnT2xkIFRvd24gUm9hZCArIFBvbnknKSA2NC1iaXREeoNlbmdnyLtFo5xfU1RBVElTVElDU19XUklUSU5HX0RBVEVfVVRDRIeTMjAxOS0xMS0xMyAxODo0ODo1OUR6g2VuZ2fIyUWjkF9TVEFUSVNUSUNTX1RBR1NEh61CUFMgRFVSQVRJT04gT" +
            "lVNQkVSX09GX0ZSQU1FUyBOVU1CRVJfT0ZfQllURVNEeoNlbmc=";

#pragma warning disable CS3016
        /// <summary>Invalid parameters count.</summary>
        /// <param name="parameters">Parameters for <see cref="Add" /> command.</param>
        /// <returns><see cref="Task" /> to execute.</returns>
        [TestCase, TestCase("", "")]
#pragma warning restore CS3016
        public static async Task InvalidParametersCount_FailureReturned(params string[] parameters) {
            var values = new List<string> { "-Add" };
            values.AddRange(parameters);
            That((await ExecuteAsync(values.ToArray()).ConfigureAwait(default)).message, EqualTo(Invalid_command_parameters_count.CurrentCultureFormat(Add, 1)));
        }

        /// <summary>Parameter file not found.</summary>
        /// <returns><see cref="Task" /> to execute.</returns>
        [Test]
        public static async Task FileNotFound_FailureReturned() => That((await ExecuteAsync("-Add", Combine(WorkingDirectory.ToString(), GetRandomFileName())).ConfigureAwait(default)).message,
            EqualTo(File_does_not_exist));

        /// <summary>MKV Tool Nix is not installed.</summary>
        /// <returns><see cref="Task" /> to execute.</returns>
        [Test]
        public static async Task MkvToolNixNotInstalled_FailureReturned() {
            var file = Combine(WorkingDirectory.ToString(), GetRandomFileName());
            Move(GetTempFileName(), file);
            That((await ExecuteAsync(collection => collection.AddSingleton(new Mock<IRegistry>().Object), "-Add", file).ConfigureAwait(default)).message, SameAs(MKV_Tool_Nix_is_not_installed));
        }

        /// <summary>MKV Tool Nix executable not found.</summary>
        /// <returns><see cref="Task" /> to execute.</returns>
        [Test]
        public static async Task MkvToolNixExecutableNotFound_FailureReturned() {
            var file = Combine(WorkingDirectory.ToString(), GetRandomFileName());
            Move(GetTempFileName(), file);
            var registry = new Mock<IRegistry>();
            // ReSharper disable StringLiteralTypo
            registry.Setup(self => self.GetValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\mkvtoolnix-gui.exe", string.Empty, default)).
                // ReSharper restore StringLiteralTypo
                Returns($@"C:\{GetRandomFileName()}");
            That((await ExecuteAsync(collection => collection.AddSingleton(registry.Object), "-Add", file).ConfigureAwait(default)).message,
                // ReSharper disable once StringLiteralTypo
                EqualTo(MKV_Tool_Nix_executable_not_found.InvariantCultureFormat(@"C:\mkvpropedit.exe")));
        }

        /// <summary>Tags added to file.</summary>
        /// <returns><see cref="Task" /> to execute.</returns>
        [SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Valid for testing."), Test]
        public static async Task FilePassed_TagsAdded() {
            Assume.That(Registry.GetValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\mkvtoolnix-gui.exe", string.Empty, default), Not.Null,
                "MKV Tool Nix needs to be installed to run this test. MKV Tool Nix can be downloaded from https://www.fosshub.com/MKVToolNix.html.");
            var file = Combine(WorkingDirectory.ToString(), GetRandomFileName());
            var fileTask = WriteAllBytesAsync(file, FromBase64String(TestMkvFile));
            var settings = new TestSettings();
            await WriteAllTextAsync(settings.TagsName.ToString(), @"<?xml version=""1.0"" encoding=""utf-8""?>
<Tags>
  <Tag>
    <Simple>
      <Name>Title</Name>
      <String>Test</String>
    </Simple>
  </Tag>
</Tags>").ConfigureAwait(default);
            await fileTask.ConfigureAwait(default);
            var size = new FileInfo(file).Length;
            var executionInformation = await ExecuteAsync(collection => collection.AddSingleton<ISettings>(settings), "-Add", file).ConfigureAwait(default);
            That(new FileInfo(file).Length, LessThan(size), () => executionInformation.message);
        }
    }
}